# docker-compose definition for developing the site.
#
version: '2'

services:
  jekyll:
    build: .
    image: aim42:site
    command: jekyll serve --trace --host 0.0.0.0 --watch --incremental --config _config.yml,_config-dev.yml
    environment:
      - JEKYLL_ENV=development
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - $PWD/_config-dev.yml:/srv/jekyll/_config-dev.yml
      - $PWD/_config.yml:/srv/jekyll/_config.yml
