services:
  jekyll:
    build:
      context: .
      dockerfile: _docker/jekyll/Dockerfile
    volumes:
      - .:/site
      - jekyll_cache:/site/.jekyll-cache
    ports:
      - "4242:4242"

volumes:
  jekyll_cache:
