# One-off conversion of the aim42 method reference (AsciiDoc, in _import/)
# into _patterns/*.md, reference pages and _data/anchors.yml.
#
#   ruby tools/migrate/run.rb                    # convert everything not yet converted
#   ruby tools/migrate/run.rb --out /tmp/x --pilot --only atam,assertions
#
# Existing pattern and page files are never overwritten: once committed, a
# converted file is the source of truth and is edited by hand. The anchor
# table, the report and the phase-page drafts in tools/migrate/out/ are
# rewritten on every run. --out writes below another root (tests), --only
# limits the run to some slugs, --pilot includes the hand-converted pilot.
require "yaml"
require "json"
require "fileutils"
require_relative "adoc_to_md"
require_relative "source"
require_relative "anchors"
require_relative "section_ids"

module Aim42
  module Migrate
    class Run
      ROOT = File.expand_path("../..", __dir__)
      ASCIIDOC = File.join(ROOT, "_import", "src", "main", "asciidoc")
      MANIFEST = File.join(__dir__, "manifest.yml")

      def initialize(out: ROOT, only: nil, pilot: false)
        @out = out
        @only = only
        @pilot = pilot
        @manifest = YAML.safe_load(File.read(MANIFEST))
        files = @manifest["patterns"].map { |p| p["source"] }.reject { |s| s.include?("#") }
        @source = Source.new(ASCIIDOC, skip: files)
        @anchors = Anchors.build(@manifest, @source)
        @converter = AdocToMd.new(@anchors)
        @slugs = @manifest["patterns"].map { |p| p["slug"] }
        @report = []
      end

      # Returns the report: [path, note] pairs.
      def call
        @manifest["patterns"].each { |entry| pattern(entry) if wanted?(entry) }
        if @only.nil?
          @manifest["pages"].each { |page| page(page) if page["target"] }
          write_anchors
          write_report
        end
        @report
      end

      private

      def wanted?(entry)
        (@only.nil? || @only.include?(entry["slug"])) && (@pilot || !entry["pilot"])
      end

      def pattern(entry)
        slug = entry["slug"]
        path = "_patterns/#{slug}.md"
        result = @converter.convert(Snippets.pattern(@source, entry), self_url: "/patterns/#{slug}/")
        notes = result.notes.dup
        body = result.body
        if entry["source"].start_with?("pattern-index.adoc#")
          intent = one_line(body)
          body = ""
        else
          intent = entry["intent"] || result.intent || index_intent(entry, notes) || lede_intent(body, notes)
          body = drop_repeated_intent(body, intent, notes)
        end
        if intent.to_s.empty?
          notes << "no intent found: write one"
          intent = "TODO"
        end
        front = { "title" => entry["title"], "phase" => entry["phase"] }
        front["categories"] = entry["categories"] if entry["categories"]
        front["intent"] = intent
        related = result.related.select { |s| @slugs.include?(s) } - [slug]
        front["related"] = related unless related.empty?
        front["status"] = body.strip.empty? ? "stub" : "complete"
        write(path, front_matter(front) + (body.strip.empty? ? "" : "\n#{body}"))
        check_images(result.images, notes)
        notes.each { |n| @report << [path, n] }
      end

      # pattern-index.adoc has a one-line description of most patterns.
      def index_intent(entry, notes)
        text = @source.index_entry(entry["anchor"])
        return nil unless text
        result = @converter.convert(text, self_url: "/patterns/#{entry["slug"]}/")
        notes.concat(result.notes)
        notes << "intent taken from pattern-index.adoc"
        one_line(result.body)
      end

      # Last resort: the first paragraph before the first heading.
      def lede_intent(body, notes)
        first = body.split(/\n{2,}/).first.to_s.strip
        return nil if first.empty? || first.start_with?("#", "*", "!", "|", ">", "`", "1.")
        notes << "intent taken from the first paragraph"
        first
      end

      def page(page)
        result = @converter.convert(Snippets.page(@source, page, @manifest), self_url: page["url"])
        front = { "title" => page["title"], "layout" => "aim42-page", "permalink" => page["url"] }
        draft = page["target"].start_with?("tools/migrate/out/")
        write(page["target"], front_matter(front) + "\n" + result.body, overwrite: draft)
        check_images(result.images, result.notes)
        result.notes.each { |n| @report << [page["target"], n] }
      end

      # The explicit anchors plus the old book's generated section ids (#_…),
      # read from the site's committed Markdown, in one key order.
      def write_anchors
        header = "# Old AsciiDoc anchor (aim42.github.io/#Anchor) → URL on this site.\n" \
                 "# Generated by tools/migrate/run.rb; read by the phase-3 redirector.\n"
        sections = SectionIds.build(ASCIIDOC, @manifest, @anchors, ROOT)
        table = @anchors.to_h
        entries = table.to_a + sections.map.reject { |id, _| table.key?(id) }.to_a
        sorted = entries.each_with_index.sort_by { |(key, _), i| [key.downcase, i] }.to_h { |entry, _| entry }
        write("_data/anchors.yml", header + sorted.to_yaml.delete_prefix("---\n"), overwrite: true)
        @anchors.duplicates.uniq.each { |a| @report << ["_data/anchors.yml", "duplicate anchor #{a}: first one wins"] }
        sections.notes.each { |note| @report << ["_data/anchors.yml", note] }
        sections.left_out.each { |id, file| @report << ["_data/anchors.yml", "section id #{id} (#{file}): dropped chapter, not mapped"] }
      end

      def write_report
        sections = @report.group_by(&:first).sort.map do |path, items|
          "## #{path}\n\n" + items.map { |_, note| "- #{note}\n" }.join
        end
        write("tools/migrate/report.md", "# Conversion report\n\n" + sections.join("\n"), overwrite: true)
      end

      def check_images(images, notes)
        images.each do |image|
          notes << "missing image images/patterns/#{image}" unless File.file?(File.join(ROOT, "images", "patterns", image))
        end
      end

      def one_line(text)
        text.gsub(/\s*\n\s*/, " ").strip
      end

      # The intent lives in front matter (spec §4): a body that opens with the
      # same text loses that paragraph.
      def drop_repeated_intent(body, intent, notes)
        first, rest = body.split(/\n{2,}/, 2)
        return body unless intent && first && one_line(first) == one_line(intent)
        notes << "first paragraph repeated the intent; removed from the body"
        rest.to_s
      end

      def front_matter(hash)
        lines = hash.map { |key, value| "#{key}: #{value.is_a?(Array) ? "[#{value.map { |v| scalar(v) }.join(", ")}]" : scalar(value)}" }
        "---\n#{lines.join("\n")}\n---\n"
      end

      # Plain YAML where it reads back unchanged, a double-quoted string otherwise.
      def scalar(value)
        plain = !value.match?(/\A[\s\-?:,\[\]{}#&*!|>'"%@`]/) && YAML.safe_load("k: #{value}")["k"] == value
        plain ? value : JSON.generate(value)
      rescue Psych::Exception
        JSON.generate(value)
      end

      def write(path, content, overwrite: false)
        target = File.join(@out, path)
        if File.exist?(target) && !overwrite
          @report << [path, "exists: not overwritten"]
          return
        end
        FileUtils.mkdir_p(File.dirname(target))
        File.write(target, content)
      end
    end
  end
end

if $PROGRAM_NAME == __FILE__
  options = {}
  args = ARGV.dup
  while (arg = args.shift)
    case arg
    when "--only" then options[:only] = args.shift.split(",")
    when "--out" then options[:out] = File.expand_path(args.shift)
    when "--pilot" then options[:pilot] = true
    else abort "unknown option #{arg}"
    end
  end
  report = Aim42::Migrate::Run.new(**options).call
  puts "#{report.size} report entries; see tools/migrate/report.md"
end
